version: '3'
services:
  app:
    image: goodness12345/studenti:1.0.0
    ports:
      - "${APP_PORT}:3030"  # Хост портът се задава динамично чрез environment variable
    environment:
      - NODE_ENV=production

